export enum Icons {
    processing = 'processing',
    marketing = 'marketing',
    profiling = 'profiling',
    provision = "provision",
    research = "research",
    security = "security",
    statistic = "statistic",
    controller = "controller",
    supervisoryAuthority = "supervisoryAuthority",
    pseudonymization = "pseudonymization",
    anonymization = "anonymization",
    automatedDecision = "automatedDecision",
    dsRights = "dsRights",
    legalBasis = "legalBasis",
    lodgeComplaint = "lodgeComplaint",
    data = "data",
    loading = "loading",
    superPurpose = "superPurpose",
    subPurpose = "subPurpose"
}